### ISSUE TITLE
Can we resurrect this project please?

### ISSUE THREAD

**Issue by phdoerfler** [freebroccolo/vscode-agda#19]
I'm taking a class on Agda which started today. So… pretty please?

**Comment by scott-fleischman** [comment]
The author of [agda-mode](https://atom.io/packages/agda-mode) on Atom has done some great work on Agda to improve the experience there, which makes things better for this project as well (should it ever rise again).

**Comment by phdoerfler** [comment]
I was indeed wondering if using the atom extension would be worth the effort. I suspect that yes it would be. Disclaimer: I got zero experience with writing Atom extensions though and only a very limited one when it comes to VS Code extensions.

**Comment by phdoerfler** [comment]
Okay nvm I dropped the lecture and quite frankly I no longer care if anything has support for Agda.
